# 【配置注意要符合yaml语法，:号后有1个空格，不能使用全角标点符号】
web:
  # 【日志记录类型】
  logtype: console
  # 【日志级别】：info、debug、error
  loglevel: info
  # 【绑定域名】用于申请ssl证书
  domain:
  # 【WEB管理界面端口】：默认80
  web_port: 80
  # 【WEB管理界面使用的HTTPS的证书和KEY的路径】，留空则不启用HTTPS
  ssl_port:
  ssl_cert:
  ssl_key: