# .github/workflows/release.yaml

on:
  push: # 每次 push 的时候触发

name: Build Release
jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/') # 只有这次 Commit 是 创建 Tag 时，才进行后续发布操作
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master # checkout 代码
      - uses: actions/setup-go@v2 # 配置 Go 环境
        with:
          go-version: "1.18.2" # 改成自己的版本

      - run: go build -o pptter_linux_amd64 ./cmd/pptter # 这 3 条是交叉编译 Go 的指令，酌情修改。
      - run: CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -o pptter_windows_amd64.exe ./cmd/pptter
      - run: CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -o pptter_darwin_amd64 ./cmd/pptter
      - run: CGO_ENABLED=0 GOOS=linux GOARCH=arm go build -o pptter_linux_arm ./cmd/pptter
      - run: CGO_ENABLED=0 GOOS=windows GOARCH=arm go build -o pptter_windows_arm ./cmd/pptter
      - run: CGO_ENABLED=0 GOOS=darwin GOARCH=arm go build -o pptter_darwin_arm ./cmd/pptter
      
      - name: Release
        uses: softprops/action-gh-release@v1
        with: # 将下述可执行文件 release 上去
          files: |
            pptter_linux_amd64
            pptter_windows_amd64.exe
            pptter_darwin_amd64
            pptter_linux_arm
            pptter_windows_arm
            pptter_darwin_arm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
